In [16]:
import pandas as pd

from numpy import array
from keras.preprocessing.text import one_hot
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Conv1D, GlobalMaxPool1D, LSTM
from keras.layers import Dense, Dropout, MaxPooling1D
from keras.layers import Flatten
from keras.layers.embeddings import Embedding

data = pd.read_csv('LABEL.txt', sep = '\t', header=None, encoding = "ISO-8859-1")

print(data)

      0                                                  1
0     0                                            15:02.3
1     0                                            23:49.1
2     0                                            55:40.6
3     0                                            59:17.1
4     0                                            00:37.2
5     0                                            00:53.2
6     0                                               1:02
7     0                                               4:01
8     0                                               4:17
9     0                                               4:18
10    0                                               4:19
11    0                                              11:22
12    0                                        0.505555556
13    0                                              12:15
14    0                                        0.640972222
15    0                                        0.6680555

In [17]:
from sklearn.model_selection import train_test_split

vocab_size = 5000

encoded_docs = [one_hot(d, vocab_size) for d in data[1]]
print(encoded_docs)

max_length = len(max(data[1])) + 1

print(max_length)

# x and y
padded_docs = pad_sequences(encoded_docs, maxlen=max_length, padding='post')
y_data = data[0]
print(padded_docs)
print(y_data)

X_train, X_test, y_train, y_test = train_test_split( padded_docs, y_data, test_size=0.2, random_state=42)

[[3341, 2865, 4484], [3950, 1597, 958], [892, 4755, 2938], [2221, 3145, 958], [1676, 3516, 2849], [1676, 302, 2849], [958, 2865], [4955, 2653], [4955, 3145], [4955, 2832], [4955, 25], [2605, 4165], [2637, 375], [3428, 3341], [2637, 1870], [2637, 3898], [3145, 1720], [2832, 2483], [2637, 1794], [3950, 1028], [3950, 4845], [958], [958, 3890], [958, 3929], [958, 958], [958, 1127], [958, 2605], [958, 4845], [958, 3341], [958, 3717], [958, 25], [958, 2849], [958, 3565], [958, 2938], [958, 2850], [958, 4655], [958, 4782], [958, 4635], [958, 4824], [958, 2355], [958, 1384], [958, 3055], [958, 498], [958, 1643], [958, 3516], [958, 3013], [958, 3341], [958, 614], [958, 3914], [958, 2062], [958, 3120], [958, 4130], [958, 3626], [958, 3564], [958, 2938], [958, 39], [958, 2827], [958, 3985], [958, 3831], [3914, 2653, 1676], [3914, 2938, 1676], [958, 1758], [958, 1107], [958, 4728], [2849], [2849, 3428], [2849, 2849], [2849, 1554], [2849, 4667], [2849, 3192], [2849, 1384], [2221, 3280, 1676], [2849

In [18]:
model = Sequential()
model.add(Embedding(vocab_size, 64, input_length=max_length))
model.add(LSTM(128))
model.add(Dense(64, activation='sigmoid'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adadelta', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, 18, 64)            320000    
_________________________________________________________________
lstm_4 (LSTM)                (None, 128)               98816     
_________________________________________________________________
dense_4 (Dense)              (None, 64)                8256      
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 65        
Total params: 427,137
Trainable params: 427,137
Non-trainable params: 0
_________________________________________________________________
None


In [19]:
#fit
model.fit(X_train, y_train, batch_size=512, epochs = 300, 
    verbose=1, validation_data= (X_test, y_test))

Train on 7510 samples, validate on 1878 samples
Epoch 1/300
7510/7510 [==============================] - 5s - loss: 0.5694 - acc: 0.7680 - val_loss: 0.5421 - val_acc: 0.7865
Epoch 2/300
7510/7510 [==============================] - 4s - loss: 0.5513 - acc: 0.7680 - val_loss: 0.5286 - val_acc: 0.7865
Epoch 3/300
7510/7510 [==============================] - 4s - loss: 0.5447 - acc: 0.7680 - val_loss: 0.5230 - val_acc: 0.7865
Epoch 4/300
7510/7510 [==============================] - 4s - loss: 0.5427 - acc: 0.7680 - val_loss: 0.5214 - val_acc: 0.7865
Epoch 5/300
7510/7510 [==============================] - 4s - loss: 0.5423 - acc: 0.7680 - val_loss: 0.5206 - val_acc: 0.7865
Epoch 6/300
7510/7510 [==============================] - 4s - loss: 0.5421 - acc: 0.7680 - val_loss: 0.5202 - val_acc: 0.7865
Epoch 7/300
7510/7510 [==============================] - 4s - loss: 0.5421 - acc: 0.7680 - val_loss: 0.5199 - val_acc: 0.7865
Epoch 8/300
7510/7510 [==============================] - 4s - loss: 0.

7510/7510 [==============================] - 4s - loss: 0.4656 - acc: 0.7680 - val_loss: 0.4850 - val_acc: 0.7865
Epoch 66/300
7510/7510 [==============================] - 4s - loss: 0.4619 - acc: 0.7680 - val_loss: 0.4816 - val_acc: 0.7865
Epoch 67/300
7510/7510 [==============================] - 4s - loss: 0.4563 - acc: 0.7680 - val_loss: 0.4767 - val_acc: 0.7865
Epoch 68/300
7510/7510 [==============================] - 4s - loss: 0.4536 - acc: 0.7680 - val_loss: 0.4781 - val_acc: 0.7865
Epoch 69/300
7510/7510 [==============================] - 4s - loss: 0.4581 - acc: 0.7680 - val_loss: 0.4880 - val_acc: 0.7865
Epoch 70/300
7510/7510 [==============================] - 4s - loss: 0.4423 - acc: 0.7680 - val_loss: 0.4751 - val_acc: 0.7865
Epoch 71/300
7510/7510 [==============================] - 4s - loss: 0.4484 - acc: 0.7680 - val_loss: 0.5043 - val_acc: 0.7865
Epoch 72/300
7510/7510 [==============================] - 4s - loss: 0.4393 - acc: 0.7680 - val_loss: 0.4792 - val_acc: 0.78

7510/7510 [==============================] - 4s - loss: 0.2828 - acc: 0.8953 - val_loss: 0.5771 - val_acc: 0.7401
Epoch 130/300
7510/7510 [==============================] - 4s - loss: 0.2817 - acc: 0.8952 - val_loss: 0.5792 - val_acc: 0.7322
Epoch 131/300
7510/7510 [==============================] - 4s - loss: 0.2731 - acc: 0.8992 - val_loss: 0.5729 - val_acc: 0.7497
Epoch 132/300
7510/7510 [==============================] - 4s - loss: 0.2731 - acc: 0.8972 - val_loss: 0.5996 - val_acc: 0.7364
Epoch 133/300
7510/7510 [==============================] - 4s - loss: 0.2739 - acc: 0.8972 - val_loss: 0.6000 - val_acc: 0.7327
Epoch 134/300
7510/7510 [==============================] - 4s - loss: 0.2743 - acc: 0.8979 - val_loss: 0.5768 - val_acc: 0.7417
Epoch 135/300
7510/7510 [==============================] - 4s - loss: 0.2699 - acc: 0.9027 - val_loss: 0.5931 - val_acc: 0.7343
Epoch 136/300
7510/7510 [==============================] - 4s - loss: 0.2706 - acc: 0.8985 - val_loss: 0.6046 - val_ac

7510/7510 [==============================] - 4s - loss: 0.2093 - acc: 0.9274 - val_loss: 0.7399 - val_acc: 0.7428
Epoch 194/300
7510/7510 [==============================] - 4s - loss: 0.2111 - acc: 0.9270 - val_loss: 0.7618 - val_acc: 0.7401
Epoch 195/300
7510/7510 [==============================] - 4s - loss: 0.2072 - acc: 0.9281 - val_loss: 0.7724 - val_acc: 0.7359
Epoch 196/300
7510/7510 [==============================] - 4s - loss: 0.2103 - acc: 0.9270 - val_loss: 0.7194 - val_acc: 0.7252
Epoch 197/300
7510/7510 [==============================] - 4s - loss: 0.2057 - acc: 0.9284 - val_loss: 0.7642 - val_acc: 0.7417
Epoch 198/300
7510/7510 [==============================] - 4s - loss: 0.2046 - acc: 0.9280 - val_loss: 0.7817 - val_acc: 0.7423
Epoch 199/300
7510/7510 [==============================] - 4s - loss: 0.2016 - acc: 0.9309 - val_loss: 0.7839 - val_acc: 0.7439
Epoch 200/300
7510/7510 [==============================] - 4s - loss: 0.1997 - acc: 0.9328 - val_loss: 0.7777 - val_ac

7510/7510 [==============================] - 4s - loss: 0.1610 - acc: 0.9529 - val_loss: 0.9045 - val_acc: 0.7364
Epoch 258/300
7510/7510 [==============================] - 4s - loss: 0.1567 - acc: 0.9561 - val_loss: 0.8709 - val_acc: 0.7476
Epoch 259/300
7510/7510 [==============================] - 4s - loss: 0.1516 - acc: 0.9594 - val_loss: 0.8547 - val_acc: 0.7476
Epoch 260/300
7510/7510 [==============================] - 4s - loss: 0.1548 - acc: 0.9569 - val_loss: 0.8359 - val_acc: 0.7503
Epoch 261/300
7510/7510 [==============================] - 4s - loss: 0.1542 - acc: 0.9573 - val_loss: 0.8843 - val_acc: 0.7407
Epoch 262/300
7510/7510 [==============================] - 4s - loss: 0.1554 - acc: 0.9573 - val_loss: 0.8843 - val_acc: 0.7449
Epoch 263/300
7510/7510 [==============================] - 4s - loss: 0.1579 - acc: 0.9551 - val_loss: 0.8608 - val_acc: 0.7444
Epoch 264/300
7510/7510 [==============================] - 4s - loss: 0.1518 - acc: 0.9586 - val_loss: 0.8992 - val_ac

In [20]:
predictions = model.predict(X_test)
print(predictions)

for i in range(len(predictions)):
    if predictions[i]>0.5:
        predictions[i] = 1
    else:
        predictions[i] = 0

print(predictions)

[[ 0.97441941]
 [ 0.79678202]
 [ 0.01871147]
 ..., 
 [ 0.01869401]
 [ 0.97370279]
 [ 0.97467208]]
[[ 1.]
 [ 1.]
 [ 0.]
 ..., 
 [ 0.]
 [ 1.]
 [ 1.]]


In [21]:
from sklearn.metrics import confusion_matrix, classification_report


print(classification_report(y_test, predictions))
confusion_matrix(y_test, predictions)



             precision    recall  f1-score   support

          0       0.41      0.42      0.41       401
          1       0.84      0.83      0.84      1477

avg / total       0.75      0.74      0.75      1878



array([[ 169,  232],
       [ 247, 1230]], dtype=int64)